### PR TITLE
Combine actions into one column

### PR DESCRIPTION
**Pull request by snake14**
### Description:

Combine actions into one column

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by snake14** [comment]
Could I please get a quick review @matomo-org/plugin-reviewers ?

**Review by AltamashShaikh — CHANGES_REQUESTED** [review]
@snake14 The changes looks good, but today during the demo it was raised that the header and the buttons are not aligned properly, can you please check that if we can align this quickly ?

Screenshot from 2024-05-28 13-20-21

**Comment by snake14** [comment]
> @snake14 The changes looks good, but today during the demo it was raised that the header and the buttons are not aligned properly, can you please check that if we can align this quickly ?
> 
> Screenshot from 2024-05-28 13-20-21

@AltamashShaikh Are they talking about the icons not lining up with the left of the header text? Unless I'm missing something, it's aligned the same way as TagManager, AbTesting, CustomDimensions, CustomReports, FormAnalytics, Goals, Funnels, and other tables.

**Comment by AltamashShaikh** [comment]
> > @snake14 The changes looks good, but today during the demo it was raised that the header and the buttons are not aligned properly, can you please check that if we can align this quickly ?
> > Screenshot from 2024-05-28 13-20-21
> 
> @AltamashShaikh Are they talking about the icons not lining up with the left of the header text? Unless I'm missing something, it's aligned the same way as TagManager, AbTesting, CustomDimensions, CustomReports, FormAnalytics, Goals, Funnels, and other tables.

@snake14 If you see, the edit icon is more on right compare to header "Action", I would suggest check with PO once, if its standard across all the pages, we can leave it as it is.

**Comment by Stan-vw** [comment]
I'm also seeing the same alignment in other tables, so I don't see that alignment needs to be addressed in this PR. We might want to look at table/column alignments as a separate piece of work though 👍

**Review by AltamashShaikh — APPROVED** [review]

**Pull request merged**
